apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: my-image:latest
          imagePullPolicy:  IfNotPresent #Always
          ports:
            - containerPort: 3000
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 3000
#            initialDelaySeconds: 5
#            periodSeconds: 10